---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Copy custom bashrc file to home directory for all users on WEB01.PROD
      copy:
        src: custom_bashrc_web.j2
        dest: "/home/{{ item }}/.bashrc"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: 0644
      with_items:
        - alex
        - andrey
        - bartek
        - lab
        - martin
        - jesus
        - pavel
        - petr
        - pmuller
        - sheila
        - vk
        - wojcikk
      when: ansible_nodename == 'web01.prod.nyc1.do.nclab.com'

    - name: Copy custom bashrc file to home directory for all users on other servers
      copy:
        src: custom_bashrc.j2
        dest: "/home/{{ item }}/.bashrc"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: 0644
      with_items:
        - alex
        - andrey
        - bartek
        - lab
        - martin
        - jesus
        - pavel
        - petr
        - pmuller
        - sheila
        - vk
        - wojcikk
      when: ansible_nodename != 'web01.prod.nyc1.do.nclab.com'
