---
- hosts: all
  #remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - name: set timezone to Pacific
      timezone:
        name: America/Los_Angeles
    - name: changing SSH server config
      template:
            src: sshd_config_template.j2
            dest: /etc/ssh/sshd_config
            owner: root
            mode: '0600'
            validate: /usr/sbin/sshd -t -f %s
            backup: yes
      notify: 
      - restart SSH 

    - name: install basic packages
      apt: 
        name: "{{ item }}" 
        state: present
      with_items:
            - 'mc'
            - 'htop'
            - 'iotop'
            - 'rsync'
            - 'vim-nox'
            - 'ntp'
            - 'ntpdate'

    - name: delete default UFW firewall
      apt:
        name: ufw
        state: absent

  handlers: 
    - name: restart SSH
      service:
        name: ssh
        state: restarted

- import_playbook: users_and_passwords.yaml
- import_playbook: ssh_keys.yaml

